# Laboratorio de Optimización

In [40]:
reset

- Importación de Paquetes

In [53]:
# importacion de paquetes de produccion
import numpy as np
import matplotlib.pyplot as plt
import simupy
from scipy import signal
from fractions import Fraction
from tkinter import *
from tkinter import ttk

- Primer punto

In [54]:
# creacion de matrices de n x m con vacancias con D. normal. Ejemplo
n = 50
index = np.random.normal(0,1,n)
index2 = np.random.normal(0,1,n)

b1 = np.array(index)
b2 = np.array(index2)

M1 = np.zeros((5,5), dtype = float, order = 'C')
M2 = np.zeros((5,5), dtype = float, order = 'C')

[f, c] = M1.shape

z = 0
ave = np.zeros(f)
for i in range(f):
    for j in range(c):
        M1[i, j] = b1[z]
        M2[i, j] = b2[z]
        z = z + 1

a.

In [55]:

def mulpow(A, B, c, d) -> None:
    condition1 = np.shape(A)
    condition2 = np.shape(B)
    if condition1[1] == condition2[0]:
        if c != 1 and condition1[0] == condition1[1]:  
            A = np.linalg.matrix_power( A, c)
        else: 
            result = 'The firts matrix cannot be powered'
        if d != 1 and condition2[0] == condition2[1]:
            B = np.linalg.matrix_power( B, d)
        else:
            result = 'The second matrix cannot be powered'
        result = np.matmul(A, B)
    else:
        result = 'Not dimensions coincidences'
    return result

if __name__ == '__main__':
    print(mulpow(M1, M2, 1 , 1))       

[[-0.57091713 -0.63334413 -0.22407312 -2.31976357  0.6871356 ]
 [ 0.51066521 -0.93486154  1.29538898 -0.70750219  0.86947997]
 [-5.00888629 -0.81108386 -3.41146576  0.46779315  1.05886875]
 [-0.93105349 -1.91278838 -1.06762276 -2.41961365  1.17626798]
 [ 0.66143122  0.63846817  0.8965237  -2.74370517 -0.01329831]]


- Segundo punto

In [56]:
A = np.matrix([[0.1,2],[2,0.1]])
B = np.matrix([[1, 2, 3],[4, 5, 6]])
C = np.matrix([[Fraction(5,3), Fraction(2,3)], [Fraction(5,3), Fraction(2,3)]])

a.

In [57]:
i = mulpow(A, B.transpose() , 1, 1)
ii = mulpow(A, B, 2, 1)
iii = mulpow(B, C, 1, 3)
iv = mulpow(B.transpose(), C, 1, 4)

b.

In [62]:
# crea la ventan de la intefaz

from unittest import result


win = Tk()

# le da dimensiones a la ventana 
win.geometry("400x120")

def save_data():
   global entry
   entrada1 = entry.get()
   entrada2 = entry2.get()
   resultado = mulpow(A, B, int(entrada1), int(entrada2))
   print(resultado)
   # label.configure(text = entrada1)

# Label de interfaz
label1 = Label(win, text ="Ingrese el valor de c:", font =("Arial 10 bold"))
label1.place(x = 50, y = 10)
# label1.pack()

# crea el frame de entrada
entry = Entry(win, width = 20)
entry.place(x = 200, y = 10)
# entry.pack()

# Label de interfaz
label2 = Label(win, text ="Ingrese el valor de d:", font =("Arial 10 bold"))
label2.place(x = 50, y = 40)
# label2.pack()

# crea el frame de entrada 
entry2 = Entry(win, width = 20)
entry2.place(x = 200, y = 40)
# entry2.pack()

# Crea el boton de ingreso
btn = ttk.Button(win, text= "Ingresar datos",width= 20, command = save_data)
btn.place(x = 200, y=65)

if __name__ == '__main__':
    win.mainloop()
else:
    print("The interface fail!")

- Tercer punto

In [108]:
# creación de la matrix
A3 = np.matrix([[3, 2, 2],[-2, 1, 4],[1, 0, 3],[5, -2, 1]])
# print(len(A3.transpose()))
# a3 = lambda M: M[1, i]*0.25 for i in range(len(A3.transpose())), M3
A3[0,:] = A3[0,:]*1/4
A3[:,1] = 3*A3[:,0] + A3[:,1]  
A3[2,:] = -1*A3[0,:] + A3[2,:]
A3[3,:] = -5*A3[0,:] + A3[3,:]
data = A3[1,:]
A3[1,:] = A3[3,:]
A3[3,:] = data